#!/bin/bash

MY_NAME=$(hostname -s)
MY_IP=$(ip addr show dev eth0 | grep inet | grep eth0 | awk '{print $2}' | awk -F/ '{print $1}')

echo "$MY_IP $MY_NAME" >> /tmp/hosts

LOCAL_GLUSTER_HOST_IP=$(etcdctl -C ${COREOS_PRIVATE_IPV4}:4001 get /glusterfs/volumes/data/hosts/${HOST})                         
cat /tmp/hosts | sed "s/^.*${HOST}$/${LOCAL_GLUSTER_HOST_IP}\t${HOST}/" > /tmp/hosts.fix
cp /tmp/hosts.fix /etc/hosts


